artifact_location: file:///Users/rajat/Desktop/projects/mlflow_demo_1/~/Desktop/projects/mlflow_demo_1/test1/0
creation_time: 1713378600964
experiment_id: '0'
last_update_time: 1713378600964
lifecycle_stage: active
name: Default
