artifact_location: file:///Users/rajat/Desktop/projects/mlflow_demo_1/~/Desktop/projects/mlflow_demo_1/test1/924162027846331254
creation_time: 1713378600967
experiment_id: '924162027846331254'
last_update_time: 1713378600967
lifecycle_stage: active
name: experiment_for_uri
